USERNAME: str = "acalimag"
PASSWORD: str = "kjt"
TEAMNAME: str = "Xrp"
EXP_DESC: str = "Test Team"
EXP_TLNAME: str = "Adam Warlock"
EXP_LOC: str = "DGT"
EXP_TYPE: str = "Operational"
EXP_ESTATUS: str = "True"
EXP_DSTATUS: str = "False"
EXT_LAST_UPD: str = "Aug 15, 2023 5:50 AM"
AGENT_NAME: str = "kleo4 test"
EXP_TLLBL: str = "TEAM LIST"
EXP_VULBL: str = "View/Update"

EXP_TBL_NAMELBL: str = "Name"
EXP_TBL_TLLBL: str = "Team Lead"
EXP_TBL_LOCLBL: str = "Location"
EXP_TBL_TYPELBL: str = "Type"
EXP_TBL_STATUSLBL: str = "Status"
EXP_TBL_LSTUPDLBL: str = "Last Updated"

EXP_VU_NAMELBL: str = "Name *"
EXP_VU_TDLBL: str = "Description"
EXP_VU_TLLBL: str = "Team Lead"
EXP_VU_LOCLBL: str = "Location *"
EXP_VU_TYPELBL: str = "Type *"
EXP_VU_STATUSLBL: str = "Status"
EXP_VU_LSTUPDLBL: str = "Last Updated"

EXP_RMNDR_LBL: str = "Reminder"
EXP_RMNDR_TXT: str = "Any changes related to the team assignment should only be done after 9AM-3AM (next day)." 