USERNAME: str = "acalimag"
PASSWORD: str = "kjt"
TEAMNAME: str = "Auto_Test_0825"
EXP_DESC: str = "Auto_Test_0825"
EXP_TLNAME: str = "Joseph Horace Calimag"
EXP_LOC: str = "DGT"
EXP_TYPE: str = "Non-Operational"
EXP_ESTATUS: str = "True"
EXP_DSTATUS: str = "False"
EXT_LAST_UPD: str = "Aug 25, 2023 4:13 AM"

AGENT_NAME: str = "kleo4 test"
EXP_TLLBL: str = "TEAM LIST"
EXP_VULBL: str = "View/Update"

EXP_TBL_NAMELBL: str = "Name"
EXP_TBL_TLLBL: str = "Team Lead"
EXP_TBL_LOCLBL: str = "Location"
EXP_TBL_TYPELBL: str = "Type"
EXP_TBL_STATUSLBL: str = "Status"
EXP_TBL_LSTUPDLBL: str = "Last Updated"

EXP_VU_NAMELBL: str = "Name *"
EXP_VU_TDLBL: str = "Description"
EXP_VU_TLLBL: str = "Team Lead"
EXP_VU_LOCLBL: str = "Location *"
EXP_VU_TYPELBL: str = "Type *"
EXP_VU_STATUSLBL: str = "Status"
EXP_VU_LSTUPDLBL: str = "Last Updated"

EXP_RMNDR_LBL: str = "Reminder"
EXP_RMNDR_TXT: str = "Any changes related to the team assignment should only be done after 9AM-3AM (next day)." 

EXP_CNTLBL: str = "Create New Team"
IN_CNT_NAME: str = "Auto_Test_0825"
IN_CNT_TD: str = "Auto_Test_0825"
IN_CNT_TL: str = "Joseph Horace Calimag"
IN_CNT_LOC: str = "DGT"
IN_CNT_TYPE: str = "Non-Operational"
IN_CNT_STATUS: str = "Disabled"

ED_VU_NAME: str = "Auto_Test_0825_1"
ED_VU_TD: str = "Auto_Test_0825_1_mod"
ED_VU_TL: str = "Adam Warlock"
ED_VU_LOC: str = "DGT"
ED_VU_TYPE: str = "Operational"
ED_VU_STATUS: str = "Enabled"