
from datetime import timedelta
from autocore.bases import WebLibraryBase
from libraries.userconfig.UserMetaCommon.dto.navbardetails import NavbarDetails


class UserMetaCommon(WebLibraryBase):
    
    def __init__(self):...
    """Browser page"""
    def open_user_config_in_browser(self):...
    def close_user_config(self):...
    def reload_user_config(self):...
    """Login"""
    def login_to_user_config(self, username: str = None, password: str = None):...
    """NavbarDetails"""
    def get_navbar_details(self, _:NavbarDetails = None) -> NavbarDetails:...
    """Landing Page"""
    def open_user_config(self):...
    def open_user_teams(self):...
    def open_aux_config(self):...
    def open_team_assignment(self):...
    def open_agent_ranking(self):...
    def open_auto_assign(self):...
    def open_call_restriction(self):...
    def open_restaurant_config(self):...
    def open_restaurant_grp(self):...
    def open_training_grp(self):...
    def elements_in_dictionary_are_visible(self, dict: dict, timeout: timedelta = None):...
    def logout_from_usermeta(self):...
    ...
    ...
    ...
    ...
    ...