from datetime import datetime
from autocore.bases import WebLibraryBase
from autocore.none import AUTOCORE_NONE


class ROSCommonLibrary(WebLibraryBase):
    
    # The ff method signatures are from libraries.ros.ROSCommonLibrary.keywords.browser.py
    def open_ros_in_browser(self):...
    def close_ros(self):...
    def reload_ros(self):...
    
    # The ff method signatures are from libraries.ros.ROSCommonLibrary.keywords.loginpage.py
    def login_to_ros(self, username:str = None, password: str = None):...
    def verify_ros_login_error_message(self):...
    def verify_ros_login_page_ui(self):...
    
    # The ff method signatures are from libraries.ros.ROSCommonLibrary.keywords.roslandingpage.py
    def search_restaurant_in_onboarding_restaurant_list(self, search_keyword: str):...
    def restaurant_details_displayed_in_onboarding_restaruant_list_should_be(self, restaurant_name: str, 
                                                                             restaurant_id: str = AUTOCORE_NONE, schedule_input: str = AUTOCORE_NONE, 
                                                                             cloned_date: str | datetime = AUTOCORE_NONE, target_go_live: str | datetime = AUTOCORE_NONE,
                                                                             day_tracker: str = AUTOCORE_NONE, task_status: str = AUTOCORE_NONE):...
    def open_create_restaurant_form_in_ros_landing_page(self):...
    def fillout_create_restaurant_form_in_ros_landing_page(self, template: str, advanced: bool = False, restaurant_name: str = AUTOCORE_NONE, restaurant_id: str = AUTOCORE_NONE,
                                       target_go_live_available: bool = True, target_go_live_date: str | datetime = AUTOCORE_NONE, save_form: bool = False):...
    def verify_create_restaurant_form_ui_in_ros_landing_page(self):...
    def open_restaurant_in_onboarding_restaurant_list(self, restaurant_name: str):...
    def logout_from_ros(self):...
    def open_list_of_live_restaurants_from_ros_landing_page(self):...