from autocore.bases import DBLibraryBase
from libraries.db.KjtDbLibrary.dto.userdetails import UserDetails
from libraries.db.KjtDbLibrary.dto.restaurantdetails import RestaurantDetails
from libraries.db.KjtDbLibrary.dto.kjtorderdetails import KjtOrderDetails
from libraries.db.KjtDbLibrary.dto.printerdetails import PrinterDetails
from libraries.db.KjtDbLibrary.dto.printtaskdetails import PrintTaskDetails
from libraries.db.KjtDbLibrary.dto.agentdetails import AgentDetails
from libraries.db.KjtDbLibrary.dto.userteamsdetails import UserTeamsDetails

class KjtDbLibrary(DBLibraryBase):
    # method signatures below this are from users.py
    def query_user_details_from_user_table(self, uid: str, _: UserDetails = None) -> UserDetails:...
    
    # method signatures below this are from restaurant.py
    def query_restaurant_details_from_restaurant_table(self, rid: str, include_html: bool = False, _: RestaurantDetails = None) -> RestaurantDetails:...
    def restaurant_type_based_on_restaurant_table_should_be(self, rid: str, exp_resto_type: str, no_check_in_prod: bool = False):...
    def restaurant_status_based_on_restaurant_table_should_be(self, rid: str, exp_status: str):...
    
    # method signatures below this are from restaurant.py
    def query_order_details_from_kjt_order_table(self, oid: str, _: KjtOrderDetails = None) -> KjtOrderDetails:...
    
    # method signatures below this are from printer.py
    def query_printer_details_of_restaurant_from_printer_table(self, rid: str, _:PrinterDetails = None) -> list[PrinterDetails]:...
    def query_details_of_printer_from_printer_table(self, pid: str, _:PrinterDetails = None) -> PrinterDetails:...
    
    # method signatures below this are from printtask.py
    def query_order_receipt_from_print_task_table(self, oid: str, version: str, order_receipt_template: str,
                                                _: PrintTaskDetails = None) -> list[PrintTaskDetails]:...
    def query_void_receipt_from_print_task_table(self, oid: str, version: str, _: PrintTaskDetails = None) -> list[PrintTaskDetails]:...
    def query_rush_receipt_from_print_task_table(self, oid: str, version: str, _: PrintTaskDetails = None) -> list[PrintTaskDetails]:...
    
    # method signatures below this are from agent.py
    def query_agent_details(self, uid: str, _: AgentDetails = None) -> AgentDetails:...

    # method signatures below this are from userteams.py
    def query_user_team_details(self, name: str, _: UserTeamsDetails = None) -> UserTeamsDetails:...