from autocore.bases import LibraryBase
from libraries.TestDataLibrary.dto.testccdetails import CreditCardDetails
from libraries.TestDataLibrary.dto.testcxdetails import TestCustomerDetails
from libraries.TestDataLibrary.dto.testrestodetails import TestRestaurantDetails
from libraries.TestDataLibrary.dto.testuserdetails import TestUserAccount


class TestDataLibrary(LibraryBase):
    def __init__(self):...
    def get_user_test_account(self, _: TestUserAccount = None) -> TestUserAccount:...
    def release_user_test_account(self):...
    def get_test_credit_card(self, card_id: str = None, _: CreditCardDetails = None) -> CreditCardDetails:...
    def get_test_customer(self, new: bool = False, _: TestCustomerDetails = None) -> TestCustomerDetails:...
    def get_test_restaurant(self, tags: str = None, _: TestRestaurantDetails = None) -> TestRestaurantDetails:...
    
    
    
    