from libraries.pos.POSCommon import POSCommon
from libraries.pos.POSRestaurantLibrary.dto.ccmodaldetails import CreditCardModalDetails
from libraries.pos.POSRestaurantLibrary.dto.orderbilldetails import OrderBillDetails
from libraries.pos.POSRestaurantLibrary.dto.selecteddishdetails import SelectedDishDetails
from libraries.pos.POSRestaurantLibrary.dto.cxorderformdetails import CustomerOrderFormDetails
from libraries.pos.POSRestaurantLibrary.dto.orderdetails import OrderDetails, DisplayedOrders
from libraries.pos.POSRestaurantLibrary.dto.voidordermodal import VoidOrderModalDetails
from libraries.pos.POSRestaurantLibrary.dto.utilmodaldetails import UtilModalDetails
from libraries.pos.POSRestaurantLibrary.dto.rushordermodaldetails import RushOrderModalDetails
from libraries.pos.POSRestaurantLibrary.dto.infomodaldetails import InfoModalDetails
from libraries.pos.POSRestaurantLibrary.dto.saveorderreasondetails import SaveOrderReasonDetails
from libraries.pos.POSRestaurantLibrary.dto.confirmmodaldetails import ConfirmModalDetails

class POSRestaurantLibrary(POSCommon):
    # The method signatures below are from libraries.pos.POSRestaurantLibrary.keywords.restaurantlanding.py
    def get_order_bill_details(self) -> OrderBillDetails:...
    def click_add_order_quantity_button(self):...
    def click_minus_order_quantity_button(self):...
    def click_save_order_button(self):...
    def click_home_button(self):...
    def click_credit_card_button(self):...
    def click_send_button(self):...
    def wait_until_restaurant_display_area_is_visible(self, en_name: str):...
    def get_details_of_the_selected_dishes(self, _: SelectedDishDetails = None) -> list[SelectedDishDetails]:...
    def click_add_sub_order_button(self):...
    def open_more_display_area(self):...
    
    # The method signatures below are from libraries.pos.POSRestaurantLibrary.keywords.fooditemsarea.py
    def select_dish_with_subtotal(self, subtotal: str, higher_than_subtotal: bool = True, dismiss_popups: bool = True):...
    def select_dish(self, count: str = 1, dish_name: str = None, dismiss_popups: bool = True):...
    
    # The method signatures below are from libraries.pos.POSRestaurantLibrary.keywords.modals.datanotify.py
    def close_all_data_notify_alerts(self):...
    def take_action_on_credit_card_minimum_data_notify_alert(self, minimum_amt: str = None, close: bool = True):...
    
    # The method signatures below are from libraries.pos.POSRestaurantLibrary.keywords.cxorderform.py
    def fill_out_customer_order_form(
            self,
            order_type: str = None,
            phone_number1: str = None,
            phone_number2: str = None,
            name: str = None,
            street: str = None,
            address_type: str = None,
            address_2: str = None,
            city: str = None,
            order_remark: str = None,
            conf_note: str = None,
            call_skill: str = None,
            dismiss_alerts: bool = True,
            _: CustomerOrderFormDetails = None
    ) -> CustomerOrderFormDetails:...
    def double_check_customer_order_form(self, form_details: CustomerOrderFormDetails):...
    def get_customer_order_form_details(self, _: CustomerOrderFormDetails = None) -> CustomerOrderFormDetails:...
    
    # The method signatures below are from libraries.pos.POSRestaurantLibrary.keywords.modals.ccmodal.py
    def fillout_credit_card_modal(self, credit_card_charge: str = None, cash_charge: str = None,
                                        tip: str = None, card_number: str = None, expi_date: str = None,
                                        cvv: str = None, postal_code: str = None, action: str = 'SUBMIT'):...
    def get_credit_card_modal_details(self, include_hints: bool = False, include_visible_fields: bool = False,
                                      _: CreditCardModalDetails = None) -> CreditCardModalDetails:...
    def credit_card_modal_should_not_be_visible(self):...
    
    # The method signatures below are from libraries.pos.POSRestaurantLibrary.keywords.moreorderlist.py
    def view_details_of_order(self, oid: str = None, phone_number: str = None, header: str = None, _: OrderDetails = None) -> OrderDetails:...
    def get_displayed_orders(self, _: DisplayedOrders = None) -> DisplayedOrders:...
    def details_of_order_should_be(self, act_order_details: OrderDetails,
                                   exp_phone1: str = None,
                                   exp_order_number: str = None,
                                   exp_order_version: str = None,
                                   exp_agent: str = None,
                                   exp_payment_type: str = None,
                                   exp_order_type: str = None,
                                   exp_order_status: str = None,
                                   exp_phone2: str = None,
                                   exp_cust_name: str = None,
                                   exp_street: str = None,
                                   exp_street2: str = None,
                                   exp_address_type: str = None,
                                   exp_city: str = None,
                                   exp_order_remark: str = None,
                                   exp_conf_note: str = None,
                                   exp_tip: str = None,
                                   exp_estimated_time: str = None,
                                   exp_new_cust_status: bool = None,
                                   exp_rush_comment: str = None,
                                   exp_void_comment: str = None
                                   ):...
    
    # The method signatures below are from libraries.pos.POSRestaurantLibrary.keywords.morelanding.py
    def click_mistake_button_on_more_display_view(self):...
    def click_repeat_button_on_more_display_view(self):...
    def click_reprint_button_on_more_display_view(self):...
    def click_void_button_on_more_display_view(self):...
    def click_rush_button_on_more_display_view(self):...
    def click_close_button_on_more_display_view(self):...
    def click_modify_button_on_more_display_view(self):...
    def get_order_bill_details_in_more_display(self) -> OrderBillDetails:...
    def get_details_of_the_ordered_dishes_in_more_display(self, _: SelectedDishDetails = None) -> list[SelectedDishDetails]:...
    
    # The method signatures below are from libraries.pos.POSRestaurantLibrary.keywords.modals.voidordermodal.py
    def take_action_on_void_order_modal(self, option: str = 'Void by owner', action: str = 'VOID',
                                        _: VoidOrderModalDetails = None) -> VoidOrderModalDetails:...
    
    # The method signatures below are from libraries.pos.POSRestaurantLibrary.keywords.modals.utilmodal.py
    def take_action_on_util_modal(self, action: str = 'NO_ACTION', check_visibility: bool = False,
                                  _: UtilModalDetails = None) -> UtilModalDetails | None:...
    
    # The method signatures below are from libraries.pos.POSRestaurantLibrary.keywords.modals.rushordermodal.py
    def take_action_on_rush_order_modal(self, option: str = 'Order takes too long, please hurry up.',
                                        action: str = 'RUSH',
                                        _: RushOrderModalDetails = None) -> RushOrderModalDetails:...
    
    # The method signatures below are from libraries.pos.POSRestaurantLibrary.keywords.modals.infomodal.py
    def take_action_on_info_modal(self, button: str = 'NO_ACTION', _: InfoModalDetails = None) -> InfoModalDetails:...
    
    # The method signatures below are from libraries.pos.POSRestaurantLibrary.keywords.modals.dispositionmodal.py
    def select_save_reason(self, option: str = None, action: str = 'CONTINUE',
                           _: SaveOrderReasonDetails = None) -> SaveOrderReasonDetails:...
    
    # The method signatures below are from libraries.pos.POSRestaurantLibrary.keywords.modals.confirmmodal.py
    def take_action_on_confirm_modal(self, input_text: str = None, button: str = 'NO_ACTION',
                                     check_visibility: bool = False,
                                     _: ConfirmModalDetails = None) -> ConfirmModalDetails | None:...
    
    # The method signatures below are from libraries.pos.POSRestaurantLibrary.keywords.helpers.libhelper.py
    def navigate_from_restaurant_to_homepage(self):...
    def send_order(self) -> str:...
    def rush_order(self, oid: str, rush_reason: str = 'Order takes too long, please hurry up.'):...
    def void_order(self, oid: str, void_reason: str = 'Customer has no money.'):...
    def force_void_order(self, phone_number: str, header: str):...
    def save_order(self, save_reason: str = 'Fax'):...
    def provide_credit_card_modal_details(self, cc_charge: str = None, cash_charge: str = None,
                                          tip: str = None, card_number: str = None, expi_date: str = None,
                                          cvv: str = None, postal_code: str = None, get_details_before: bool = False,
                                          get_details_after: bool = False, action: str = 'SUBMIT',
                                          _: CreditCardModalDetails = None) -> CreditCardModalDetails | None:...
    
    # The method signatures below are from libraries.pos.POSRestaurantLibrary.keywords.helpers.stringhelper.py
    def extract_credit_card_minimum(self, credit_card_info: str) -> tuple:...