MODAL: str = "//div[@id='creditCardModal']//div[@class='modal-dialog']"
CONFIRM_INFO_BOX: str = "id:ccforminfobox"
CC_CHARGE_FLD: str = "xpath://label[text()='Credit Card Charge:']//following-sibling::input[@id='creditCharge']"
CASH_CHARGE_FLD: str = "xpath://label[text()='Cash Charge:']//following-sibling::input[@id='cashCharge']"
TIP_CHARGE_FLD: str = "xpath://label[text()='Tip:']//following-sibling::input[@id='tipCharge']"
PAY_CASH_INSTEAD_BTN: str = "xpath://button[text()='Pay cash instead' and @id='payCash']"
ADD_ON_PAY_CASH_BTN: str = "xpath://button[text()='Add on pay cash' and @id='addOnCash']"
ADD_ON_PAY_CREDIT_CARD: str = "xpath://button[text()='Add on Pay Credit Card' and @id='payCredit']"
CREDIT_AMOUNT_ERROR: str = "id:creditAmountError"
CASH_AMOUNT_ERROR: str = "id:cashAmountError"

PROPAY_IFRAME: str = "xpath://*[@id='propayForm']//iframe"
PROPAY_CARD_NUMBER: str = "id:txtCardNumber"
PROPAY_EXP_MONTH_SELECT: str = "id:ddlExpDateMonth"
PROPAY_EXP_YEAR_SELECT: str = "id:ddlExpDateYear"
PROPAY_CVV: str = "id:txtCvv"
PROPAY_POSTAL_CODE: str = "id:txtZip"
PROPAY_SUBMIT: str = "id:btnSubmit"
PROPAY_CANCEL: str = "id:closeCardModal"
PROPAY_VALIDATION_MSG: str = "id:ValidationMessage"
PROPAY_CARD_NUMBER_VALIDATION_MSG: str = "xpath://span[@id='validationMsgCardNumber']/span"
PROPAY_CVV_VALIDATION_MSG: str = "xpath://span[@id='validationMsgCvv']/span"

NON_PROPAY_CC_NUMBER: str = "id:ccnumber"
NON_PROPAY_EXPI_DATE: str = "id:expdate"
NON_PROPAY_CVC: str = "id:cvc"
NON_PROPAY_ZIP: str = "id:zip"
NON_PROPAY_CLEAR: str = "id:clear"
NON_PROPAY_CANCEL: str = "id:closeCardModal"
NON_PROPAY_DONE: str = "id:done"
NON_PROPARY_CC_NUM_ERR_MSG: str = "id:ccnumberError"
NON_PROPAY_EXPI_DATE_ERR_MSG: str = "id:expdateError"
NON_PROPAY_CVV_ERR_MSG: str = "id:cvcError"
NON_PROPAY_ZIP_ERR_MSG: str = "id:zipError"
NON_PROPAY_REPEAT_EXPI: str = "id:repeatExp"
NON_PROPAY_REPEAT_CVV: str = "id:repeatCvc"
NON_PROPAY_REPEAT_ZIP: str = "id:repeatZip"

EXISTING_CARD_NUMBER: str = "xpath://p[text()='Existing Credit Card']//following-sibling::p[@id='propayCardNumber']"
EXISTING_UPDATE_CARD_BTN: str = "id:propayNewCard"
EXISTING_DONE: str = "id:done"
EXISTING_CLOSE: str = "id:closePropayButton"
