from libraries.dashboard.ClientTechDashboardLibrary.dto.acknowledgemodaldetails import AcknowdledgeModalDetails
from libraries.dashboard.DashboardCommon import DashboardCommon


class ClientTechDashboardLibrary(DashboardCommon):
    
    def __init__(self):...
    def wait_until_client_tech_dashboard_is_visible(self):...
    def printer_should_not_be_visible_in_the_main_printer_section(self, printer_name: str):...
    def take_action_on_acknowledge_modal(self, action: str = 'OK', _:AcknowdledgeModalDetails = None) -> AcknowdledgeModalDetails:...
    def main_printer_details_should_be(self, printer_name: str, exp_status: str = None,exp_description: str = None):...
    def ack_printer_details_should_be(self, printer_name: str, exp_status: str = None,exp_description: str = None):...
    def printer_should_not_be_visible_in_the_ack_printer_section(self, printer_name: str):...
    def click_printer_close_btn(self, printer_name: str):...
    def main_port_details_should_be(self, en_name: str, ex_name: str, exp_gateway: str, exp_status: str = None, exp_description: str = None):...
    def ack_port_details_should_be(self, en_name: str, ex_name: str, exp_gateway: str, exp_status: str = None, exp_description: str = None):...
    def restaurant_should_not_be_visible_in_the_ack_port_section(self, en_name: str, ex_name: str):...
    def click_restaurant_close_btn(self, en_name: str, ex_name: str):...
    
    