from libraries.contentconfig.ContentConfigCommon import ContentConfigCommon
from libraries.contentconfig.PrinterEditorLibrary.dto.printerdetails import PrinterDetails

class PrinterEditorLibrary(ContentConfigCommon):
    def __init__(self):...
    def open_restaurant_in_printer_editor(self, en_name: str, ex_name: str):...
    def get_printer_details(self, pid: str, incl_dd_options: bool = False, incl_nucless_details: bool = False,
                            incl_err_msgs: bool = False, _: PrinterDetails = None) -> PrinterDetails:...
    def enable_nucless_in_printer_editor(self):...
    def disable_nucless_in_printer_editor(self):...
    def check_active_checkbox(self, pid: str):...
    def uncheck_active_checkbox(self, pid: str):...
    def check_customer_info_text(self, pid: str):...
    def uncheck_customer_info_text(self, pid: str):...
    def check_chinese_text(self, pid: str):...
    def uncheck_chinese_text(self, pid: str):...
    def check_english_text(self, pid: str):...
    def uncheck_english_text(self, pid: str):...
    def check_always_print_qty(self, pid: str):...
    def uncheck_alwasy_print_qty(self, pid: str):...
    def check_modified_dishes_only(self, pid: str):...
    def uncheck_modified_dishes_only(self, pid: str):...
    def check_cc_void_receipt(self, pid: str):...
    def uncheck_cc_void_receipt(self, pid: str):...
    def turn_on_chinese_text_bold(self, pid: str):...
    def turn_off_chinese_text_bold(self, pid: str):...
    def turn_on_english_text_bold(self, pid: str):...
    def turn_off_english_text_bold(self, pid: str):...
    def save_printer_details(self, action: str = 'SAVE'):...
    def click_add_printer(self):...
    def update_pid(self, pid: str, new_pid: str):...
    def fillout_other_printer_details(self, pid: str, name: str = None, mask: str = None, mask_rule: str = None,
                                      order_receipt_tpl: str = None, cx_info_txt_font_size: str = None, ch_text_font_size: str = None,
                                      en_text_font_size: str = None, spacing: str = None, line: str = None, cc_template: str = None,
                                      host: str = None, model: str = None, printer_port: str = None, status_port: str = None, new_printer: bool = False):...
    def printer_should_be_active(self, pid: str, ):...
    def printer_should_not_be_active(self, pid: str, ):...
    def printer_details_should_be(self, pid: str, name: str = None, mask: str = None, mask_rule: str = None, order_receipt_tpl: str = None,
                                  line: str = None, cc_template: str = None, last_updated: str = None, last_updated_by: str = None, cx_info_txt_font_size: str = None,
                                  cn_txt_font_size: str = None, en_txt_font_size: str = None, spacing: str = None, active: str = None, nucless: str = None):...
    def nucless_details_should_be(self, pid: str, host: str = None, model: str = None, printer_port: str = None, status_port: str = None):...
    def customer_info_text_checkbox_should_be_disabled(self, pid: str):...
    def customer_info_text_checkbox_should_be_enabled(self, pid: str):...
    def customer_info_text_font_size_should_be_enabled(self, pid: str):...
    def customer_info_text_font_size_should_be_disabled(self, pid: str):...
    def chinese_text_font_size_should_be_enabled(self, pid: str):...
    def chinese_text_font_size_should_be_disabled(self, pid: str):...
    def chinese_text_checkbox_should_be_enabled(self, pid: str):...
    def chinese_text_checkbox_should_be_disabled(self, pid: str):...
    def chinese_text_toggle_should_be_enabled(self, pid: str):...
    def chinese_text_toggle_should_be_selected(self, pid: str):...
    def chinese_text_toggle_should_not_be_selected(self, pid: str):...
    def chinese_text_toggle_should_be_disabled(self, pid: str):...
    def english_text_font_size_should_be_enabled(self, pid: str):...
    def english_text_font_size_should_be_disabled(self, pid: str):...
    def english_text_checkbox_should_be_enabled(self, pid: str):...
    def english_text_checkbox_should_be_disabled(self, pid: str):...
    def english_text_toggle_should_be_enabled(self, pid: str):...
    def english_text_toggle_should_be_disabled(self, pid: str):...
    def english_text_toggle_should_be_selected(self, pid: str):...
    def english_text_toggle_should_not_be_selected(self, pid: str):...
    def spacing_should_be_enabled(self, pid: str):...
    def spacing_should_be_disabled(self, pid: str):...
    def always_print_qty_should_be_enabled(self, pid: str):...
    def always_print_qty_should_be_disabled(self, pid: str):...
    def modified_dishes_only_should_be_enabled(self, pid: str):...
    def modified_dishes_only_should_be_disabled(self, pid: str):...
    def line_should_be_enabled(self, pid: str):...
    def line_should_be_disabled(self, pid: str):...
    def customer_info_text_checkbox_should_be_selected(self, pid: str):...
    def customer_info_text_checkbox_should_not_be_selected(self, pid: str):...
    def chinese_text_checkbox_should_be_selected(self, pid: str):...
    def chinese_text_checkbox_should_not_be_selected(self, pid: str):...
    def english_text_checkbox_should_be_selected(self, pid: str):...
    def english_text_checkbox_should_not_be_selected(self, pid: str):...
    def always_print_qty_checkbox_should_be_selected(self, pid: str):...
    def always_print_qty_checkbox_should_not_be_selected(self, pid: str):...
    def modified_dishes_only_checkbox_should_be_selected(self, pid: str):...
    def modified_dishes_only_checkbox_should_not_be_selected(self, pid: str):...
    def cc_void_receipt_checkbox_should_be_selected(self, pid: str):...
    def cc_void_receipt_checkbox_should_not_be_selected(self, pid: str):...
    def printer_editor_error_messages_should_be(self, pid: str, pid_err_msg: str = None, name_err_msg: str = None, mask_err_msg: str = None,
                                                mask_rule_err_msg: str = None, order_receipt_tpl_err: str = None,
                                                host_err_msg: str = None, model_err_msg: str = None, printer_port_err_msg: str = None,
                                                status_port_err_msg: str = None):...
    def printer_editor_page_column_names_should_include(self, *args):...
    def printer_editor_page_column_count_should_be(self, count: str):...
    def nucless_details_column_names_should_include(self, *args):...
    def nucless_details_column_count_should_be(self, count: str):...
    def template_settings_should_be_correct(self, pid: str,  db_template_setting: str):...
    def add_printer_button_should_be_visible(self, enabled: bool = None):...
    def save_printer_button_should_be_visible(self, enabled: bool = None):...
    def nucless_details_should_not_be_visible(self):...
    def last_updated_time_should_be_visible(self, pid: str):...
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    