
from autocore.bases import WebLibraryBase
from libraries.contentconfig.ContentConfigCommon.dto.navbardetails import NavbarDetails


class ContentConfigCommon(WebLibraryBase):
    
    def __init__(self):...
    def open_content_config_in_browser(self):...
    def close_content_config(self):...
    def reload_content_config(self):...
    def login_to_content_config(self, username: str = None, password: str = None):...
    def open_printer_editor(self):...
    def open_propay_account_editor(self):...
    def open_credit_card_not_editor(self):...
    def open_wonderspay_terminal_editor(self):...
    def get_navbar_details(self, _:NavbarDetails = None) -> NavbarDetails:...
    
    