from autocore.bases import WebLibraryBase


class DashboardCommon(WebLibraryBase):
    def __init__(self):...
    def open_dashboard_in_browser(self):...
    def close_dashboard(self):...
    def reload_dashboard(self):...
    def login_to_dashboard(self, username: str = None, password: str = None):...
    def go_to_client_tech_dashboard(self):...